Controllers/PostModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudioSintoniaPreview.Data;
using StudioSintoniaPreview.Entities;
using StudioSintoniaPreview.Models;

namespace StudioSintoniaPreview.Controllers
{
    public class PostModelsController : Controller
    {
        private readonly BancoContext _context;
        private string caminhoServidor;
        private readonly UserManager<IdentityUser> _userManager;

        public PostModelsController(BancoContext context, IWebHostEnvironment Sistema, UserManager<IdentityUser> userManager)
        {
            _context = context;
            caminhoServidor = Sistema.WebRootPath;
            _userManager = userManager;
        }

        // GET: PostModels9
        public async Task<IActionResult> Index()
        {
            var usuario = await _userManager.GetUserAsync(User);
            var bancoContext = _context.Posts.Where(p => p.UsuarioModelId == usuario!.Id);
            return View(await bancoContext.ToListAsync());
        }

        [HttpPost]
        public JsonResult CurtiPost(int postId)
        {
            var post = _context.Posts.Find(postId);
            if (post != null)
            {
                
                post.Curtido = !post.Curtido; // Alterna o estado de curtida
                _context.Update(post);
                _context.SaveChanges();
                return Json(new { success = true, isLiked = post.Curtido });
            }
            return Json(new { success = false });
        }

        [HttpGet]
        public async Task<IActionResult> BuscarCurtidas()
        {
            var result =  _context.Posts.Where(p => p.Curtido == true);
            return View(result);
        }

        public async Task<IActionResult> Feed()
        {
            var bancoContext = await _context.Posts.ToListAsync();
            return View(bancoContext);
        }

        // GET: PostModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _userManager.GetUserAsync(User);
            var postModel = await _context.Posts
                .Where(p => p.UsuarioModelId == usuario!.Id)
                .FirstOrDefaultAsync(m => m.PostModelId == id);
            if (postModel == null)
            {
                return NotFound();
            }

            return View(postModel);
        }

        // GET: PostModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PostModels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostModel postModel)
        {
            if (ModelState.IsValid)
            {
                // Pega ID do usuário logado
                var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
                postModel.UsuarioModelId = userId;

                // Se o post tiver imagem, salvar na wwwroot e o nome do arquivo na prop "Conteudo"
                if (postModel.MetaDadosImagem is not null)
                {
                    string caminhoParaSalvarArquivo = Path.Combine(caminhoServidor, "arquivos");
                    string guid = Guid.NewGuid().ToString();
                    string novoNomeParaArquivo = $"{guid}_{postModel.MetaDadosImagem.FileName}";

                    if (!Directory.Exists(caminhoParaSalvarArquivo))
                    {
                        Directory.CreateDirectory(caminhoParaSalvarArquivo);
                    }

                    string caminhoCompleto = Path.Combine(caminhoParaSalvarArquivo, novoNomeParaArquivo);

                    using (var stream = new FileStream(caminhoCompleto, FileMode.Create))
                    {
                        await postModel.MetaDadosImagem.CopyToAsync(stream);
                    }

                    postModel.Conteudo = novoNomeParaArquivo; // Salva o nome do arquivo com o GUID no banco
                }

                // Adiciona postagem no banco
                _context.Add(postModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // ViewData["UsuarioModelId"] = new SelectList(_context.Usuarios, "UsuarioModelId", "UsuarioModelId", postModel.UsuarioModelId);
            return View(postModel);
        }


        // GET: PostModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postModel = await _context.Posts.FindAsync(id);
            if (postModel == null)
            {
                return NotFound();
            }
            //ViewData["UsuarioModelId"] = new SelectList(_context.Usuarios, "UsuarioModelId", "UsuarioModelId", postModel.UsuarioModelId);
            return View(postModel);
        }

        // POST: PostModels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostModelId,TagId,UsuarioModelId,Conteudo,Descricao,Curtidas,Valor")] PostModel postModel)
        {
            if (id != postModel.PostModelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(postModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostModelExists(postModel.PostModelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            // ViewData["UsuarioModelId"] = new SelectList(_context.Usuarios, "UsuarioModelId", "UsuarioModelId", postModel.UsuarioModelId);
            return View(postModel);
        }

        // GET: PostModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _userManager.GetUserAsync(User);
            var postModel = await _context.Posts
                .Where(p => p.UsuarioModelId == usuario.Id)
                .FirstOrDefaultAsync(m => m.PostModelId == id);
            if (postModel == null)
            {
                return NotFound();
            }

            return View(postModel);
        }

        // POST: PostModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var postModel = await _context.Posts.FindAsync(id);
            if (postModel != null)
            {
                _context.Posts.Remove(postModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostModelExists(int id)
        {
            return _context.Posts.Any(e => e.PostModelId == id);
        }
    }
}

Views/Shared/Modal.cshtml
@model StudioSintoniaPreview.Models.PostModel

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Novo Post</h5>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form method="post" asp-controller="PostModels" asp-action="Create" enctype="multipart/form-data">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label>Escolha seu arquivo</label>
                                <input asp-for="MetaDadosImagem" id="MetaDadosImagem" name="MetaDadosImagem" type="file" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label asp-for="Descricao" class="control-label"></label>
                                <input asp-for="Descricao" class="form-control" />
                                <span asp-validation-for="Descricao" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Valor" class="control-label"></label>
                                <input asp-for="Valor" class="form-control" />
                                <span asp-validation-for="Valor" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Postar" class="btn btn-primary m-2" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Studio_Sintonia</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Styles.css" />
    <link rel="stylesheet" href="~/css/Player.css" />
    <link rel="stylesheet" href="~/css/Perfil.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">

    @RenderSection("Styles", required: false)
</head>
@{
    var currentAction = ViewContext.RouteData.Values["action"]?.ToString();
    var currentController = ViewContext.RouteData.Values["controller"]?.ToString();
    var isLoginPage = currentController.Equals("Account", StringComparison.OrdinalIgnoreCase) && currentAction.Equals("Login", StringComparison.OrdinalIgnoreCase);
    var isRegisterPage = currentController.Equals("Account", StringComparison.OrdinalIgnoreCase) && currentAction.Equals("Register", StringComparison.OrdinalIgnoreCase);
    var hideSidebar = isLoginPage || isRegisterPage;
}

<body>
    <div class="container-fluid">
        <div class="row">
            @if (!hideSidebar)
            {
                <div class="col-sm-2">
                    <!-- Barra Lateral -->
                    <aside>
                        <div class="toggle">
                            <div class="logo">
                                @* <img src="~/lib/Studio Sintonia.png" /> *@
                                <h2>Studio<span class="danger">Sintonia</span></h2>
                            </div>
                        </div>
                        <div class="sidebar">
                            <a class="nav-link" asp-controller="PostModels" asp-action="Feed">
                                <i class="fas fa-home"></i>
                                <h3>Feed</h3>
                            </a>
                            <a class="nav-link" asp-controller="PostModels" asp-action="Index">
                                <i class="fas fa-user"></i>
                                <h3>Perfil</h3>
                            </a>
                            <a class="nav-link" asp-controller="PostModels" asp-action="BuscarCurtidas">
                                <i class="fas fa-heart"></i>
                                <h3>Curtidas</h3>
                            </a>
                            <a class="nav-link" asp-controller="Home" asp-action="Dashboard">
                                <i class="fas fa-chart-bar"></i>
                                <h3>Analytics</h3>
                            </a>
                            @* <a class="nav link" asp-controller="UsuarioModels" asp-action="Index">
                        <i class="fas fa-sign-out-alt"></i>
                        <h3>Logout</h3>
                        </a> *@

                            <partial name="_LoginPartial.cshtml" />
                        </div>
                    </aside>
                </div>
            }
            <div class="@(hideSidebar ? "col-sm-12" : "col-sm-10")">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
@*     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>